/* Generated by CMake. Do not edit. */

/* Determined C standard version from CMake (0 if unknown) */
#define CMAKECFG_STDC_VERSION @CMAKECFG_STDC_VERSION@

/* Determined pointer size in bytes */
#define CMAKECFG_SIZEOF_VOID_P @CMAKECFG_SIZEOF_VOID_P@
