#ifndef CATCRLIB_HPP
#define CATCRLIB_HPP
#include "CATCRLIB.h"
namespace catalyst {

/* -------------------------------------------------------------------------------------------------
 * C++ API :: NUMERICS
 * ------------------------------------------------------------------------------------------------- */

typedef ::CATALYST_BYTE BYTE;
typedef ::CATALYST_SBYTE SBYTE;

#if CATCRLIB_SUPPORTS_16BIT
    typedef ::CATALYST_SHORT SHORT;
    typedef ::CATALYST_USHORT USHORT;
#endif

#if CATCRLIB_SUPPORTS_32BIT
    typedef ::CATALYST_INT INT;
    typedef ::CATALYST_UINT UINT;
#endif

#if CATCRLIB_SUPPORTS_64BIT
    typedef ::CATALYST_LONG LONG;
    typedef ::CATALYST_ULONG ULONG;
#endif

#if CATCRLIB_SUPPORTS_SINGLE
    typedef ::CATALYST_SINGLE SINGLE;
#endif

#if CATCRLIB_SUPPORTS_DOUBLE
    typedef ::CATALYST_DOUBLE DOUBLE;
#endif

typedef ::CATALYST_BOOL BOOL;
typedef ::CATALYST_NINT NINT;
typedef ::CATALYST_NUINT NUINT;

static const BOOL TRUE = CATALYST_TRUE;
static const BOOL FALSE = CATALYST_FALSE;

/* -------------------------------------------------------------------------------------------------
 * C++ API :: TEXT ENCODING
 * ------------------------------------------------------------------------------------------------- */


typedef ::CATALYST_TEXT_ENCODING TEXT_ENCODING;

static const TEXT_ENCODING TEXT_ENCODING_UNKNOWN = ::CATALYST_TEXT_ENCODING_UNKNOWN;
static const TEXT_ENCODING TEXT_ENCODING_ASCII = ::CATALYST_TEXT_ENCODING_ASCII;
static const TEXT_ENCODING TEXT_ENCODING_CP1252 = ::CATALYST_TEXT_ENCODING_CP1252;
static const TEXT_ENCODING TEXT_ENCODING_UTF8 = ::CATALYST_TEXT_ENCODING_UTF8;
static const TEXT_ENCODING TEXT_ENCODING_UTF16LE = ::CATALYST_TEXT_ENCODING_UTF16LE;

typedef ::CATALYST_CODEPOINT CODEPOINT;

typedef ::CATALYST_ASCII_CODE_UNIT ASCII_CODE_UNIT;
typedef ::CATALYST_ASCIIW ASCIIW;
typedef ::CATALYST_ASCII ASCII;

typedef ::CATALYST_CP1252_CODE_UNIT CP1252_CODE_UNIT;
typedef ::CATALYST_CP1252W CP1252W;
typedef ::CATALYST_CP1252 CP1252;

typedef ::CATALYST_UTF8_CODE_UNIT UTF8_CODE_UNIT;
typedef ::CATALYST_UTF8W UTF8W;
typedef ::CATALYST_UTF8 UTF8;

typedef ::CATALYST_UTF16LE_CODE_UNIT UTF16LE_CODE_UNIT;
typedef ::CATALYST_UTF16LEW UTF16LEW;
typedef ::CATALYST_UTF16LE UTF16LE;

/* -------------------------------------------------------------------------------------------------
 * C++ API :: OPERATION STATUS
 * ------------------------------------------------------------------------------------------------- */

typedef ::CATALYST_STATUS_CODE STATUS_CODE;

static const STATUS_CODE STATUS_CODE_SUCCESS = ::CATALYST_STATUS_CODE_SUCCESS;
static const STATUS_CODE STATUS_CODE_SUCCESS_NOOP = ::CATALYST_STATUS_CODE_SUCCESS_NOOP;

static const STATUS_CODE STATUS_CODE_WARNING = ::CATALYST_STATUS_CODE_WARNING;
static const STATUS_CODE STATUS_CODE_WARNING_PARTIAL = ::CATALYST_STATUS_CODE_WARNING_PARTIAL;
static const STATUS_CODE STATUS_CODE_WARNING_DEPRECATED = ::CATALYST_STATUS_CODE_WARNING_DEPRECATED;

static const STATUS_CODE STATUS_CODE_ERROR = ::CATALYST_STATUS_CODE_ERROR;
static const STATUS_CODE STATUS_CODE_ERROR_INVALID_ARGUMENT = ::CATALYST_STATUS_CODE_ERROR_INVALID_ARGUMENT;
static const STATUS_CODE STATUS_CODE_ERROR_INVALID_STATE = ::CATALYST_STATUS_CODE_ERROR_INVALID_STATE;
static const STATUS_CODE STATUS_CODE_ERROR_MALFORMED_INPUT = ::CATALYST_STATUS_CODE_ERROR_MALFORMED_INPUT;
static const STATUS_CODE STATUS_CODE_ERROR_ACCESS_DENIED = ::CATALYST_STATUS_CODE_ERROR_ACCESS_DENIED;
static const STATUS_CODE STATUS_CODE_ERROR_NOT_IMPLEMENTED = ::CATALYST_STATUS_CODE_ERROR_NOT_IMPLEMENTED;
static const STATUS_CODE STATUS_CODE_ERROR_SYSTEM_NOT_SUPPORTED = ::CATALYST_STATUS_CODE_ERROR_SYSTEM_NOT_SUPPORTED;
static const STATUS_CODE STATUS_CODE_ERROR_TIMEOUT = ::CATALYST_STATUS_CODE_ERROR_TIMEOUT;
static const STATUS_CODE STATUS_CODE_ERROR_NOT_FOUND = ::CATALYST_STATUS_CODE_ERROR_NOT_FOUND;
static const STATUS_CODE STATUS_CODE_ERROR_INTERRUPTED = ::CATALYST_STATUS_CODE_ERROR_INTERRUPTED;
static const STATUS_CODE STATUS_CODE_ERROR_DEPENDENCY_FAILURE = ::CATALYST_STATUS_CODE_ERROR_DEPENDENCY_FAILURE;
static const STATUS_CODE STATUS_CODE_ERROR_BUFFER_OVERFLOW = ::CATALYST_STATUS_CODE_ERROR_BUFFER_OVERFLOW;
static const STATUS_CODE STATUS_CODE_ERROR_ALLOCATION_FAILED = ::CATALYST_STATUS_CODE_ERROR_ALLOCATION_FAILED;
static const STATUS_CODE STATUS_CODE_ERROR_IO_ERROR = ::CATALYST_STATUS_CODE_ERROR_IO_ERROR;

static const STATUS_CODE STATUS_CODE_FATAL = ::CATALYST_STATUS_CODE_FATAL;
static const STATUS_CODE STATUS_CODE_FATAL_INVARIANT_VIOLATION = ::CATALYST_STATUS_CODE_FATAL_INVARIANT_VIOLATION;

static const STATUS_CODE STATUS_CODE_LEVEL_MASK = CATALYST_STATUS_CODE_LEVEL_MASK;

inline BOOL statusCodeIsSuccess(STATUS_CODE status) {
    return CATALYST_STATUS_CODE_IS_SUCCESS(status) ? TRUE : FALSE;
}

inline BOOL statusCodeIsWarning(STATUS_CODE status) {
    return CATALYST_STATUS_CODE_IS_WARNING(status) ? TRUE : FALSE;
}

inline BOOL statusCodeIsError(STATUS_CODE status) {
    return CATALYST_STATUS_CODE_IS_ERROR(status) ? TRUE : FALSE;
}

inline BOOL statusCodeIsFatal(STATUS_CODE status) {
    return CATALYST_STATUS_CODE_IS_FATAL(status) ? TRUE : FALSE;
}

typedef ::CATALYST_CONTEXT_CODE CONTEXT_CODE;
typedef ::CATALYST_OPERATION_CODE OPERATION_CODE;
typedef ::CATALYST_DETAIL_CODE DETAIL_CODE;

static const CONTEXT_CODE CONTEXT_CODE_NONE = (CONTEXT_CODE) 0x00;
static const OPERATION_CODE OPERATION_CODE_NONE = (OPERATION_CODE) 0x00;
static const DETAIL_CODE DETAIL_CODE_NONE = (DETAIL_CODE) 0x00;

typedef ::CATALYST_RESULT RESULT;

} /* namespace catalyst */
#endif /* CATCRLIB_HPP */
